# Build the C# windows form application when receiving a pull request

name: Build for pull request

on:
  pull_request:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

    - name: Setup NuGet
      uses: nuget/setup-nuget@d105a947828025cd7a980103c35ba2bfae586d0f # v2.0.2

    - name: Restore NuGet packages
      run: nuget restore 2LCS/2LCS.csproj

    - name: Build
      run: msbuild 2LCS/2LCS.csproj /p:VersionSuffix=pr /p:Configuration=Release /p:Version=0.0.0.${{ github.event.pull_request.number }} /p:InformationalVersion=0.0.0.${{ github.event.pull_request.number }}-pr

    - name: Upload 2LCS.zip
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: 2LCS
        path: 2LCS/bin/Release    
